# This is a sample script to submit the jobs built using the sample Makefile
# The main purpose is to highlight the submitjob commands that you will then 
# modify to fit the environment that you are in. 

streamtool submitjob --jobname PacketHandler  --embeddedzk  -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.packethandler::PacketHandler.connHost=127.0.0.1 -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.packethandler::PacketHandler.connPort=33333 -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.packethandler::PacketHandler.controlDiagnostics=/home/streamsadmin/data/  output/packethandler/com.ibm.streamsx.speech2text.callcenter.speechprocessing.packethandler.PacketHandler.sab 

streamtool submitjob --jobname WatsonSpeech2Text1  --embeddedzk -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.diagnostics=/home/streamsadmin/data/ -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.paramsetFile=/home/streamsadmin/toolkits/model/rapid231/EnUS_Telephony_r2.3.1-8kHz-diarization.pset -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.packageFile=/home/streamsadmin/toolkits/model/rapid231/EnUS_Telephony_r2.3.1.pkg -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.utterances=/home/streamsadmin/data/ -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.callCenter=67 output/watsonspeech2text1/com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t.WatsonSpeech2Text.sab

streamtool submitjob --jobname DataCenterSink  --embeddedzk -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.datacentersink::DataCenterSink.connPort=21436 output/datacentersink/com.ibm.streamsx.speech2text.callcenter.speechprocessing.datacentersink.DataCenterSink.sab

streamtool submitjob --jobname WavGenerator --embeddedzk output/wavgen/com.ibm.streamsx.speech2text.callcenter.speechprocessing.wavgen.WavGenerator.sab -P moveToDirectory=/tmp/Speech2Text/wavGen/moveToDir -P writeBINLocation=/tmp/Speech2Text/wavGen/writeBin -P writeWAVLocation=/tmp/Speech2Text/wavGen/writeWAV -P writeToDirectory=/tmp/Speech2Text/wavGen/writeToDir -P ffmpegLocation=/home/streamsadmin/ffmpeg/ffmpeg-3.2-64bit-static/
