# This is a sample script to submit the jobs 
# The main purpose is to highlight the submitjob commands that you will then 
# modify to fit the environment that you are in. 

streamtool submitjob --jobname PacketHandler  --embeddedzk  -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.packethandler::PacketHandler.connHost=127.0.0.1 -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.packethandler::PacketHandler.connPort=23146 -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.packethandler::PacketHandler.controlDiagnostics=/home/streamsadmin/data/  -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.packethandler::PacketHandler.numWatsonHosts=2 -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.packethandler::PacketHandler.watsonEngineCountList='[2,3]' -g etc/packetHandlerJobConfig.json output/packethandler/com.ibm.streamsx.speech2text.callcenter.speechprocessing.packethandler.PacketHandler.sab 

streamtool submitjob --jobname WatsonSpeech2Text1  --embeddedzk -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.diagnostics=/home/streamsadmin/data/ -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.paramsetFile=/home/streamsadmin/toolkits/model/rapid231/EnUS_Telephony_r2.3.1-8kHz-diarization.pset -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.packageFile=/home/streamsadmin/toolkits/model/rapid231/EnUS_Telephony_r2.3.1.pkg -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.utterances=/home/streamsadmin/data/ -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.callCenter=67 -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.watsonJobId=0 -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.numWatsonEngines=2 -g etc/watsonJobConfig1.json output/watsonspeech2text/com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t.WatsonSpeech2Text.sab

streamtool submitjob --jobname WatsonSpeech2Text2  --embeddedzk -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.diagnostics=/home/streamsadmin/data/ -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.paramsetFile=/home/streamsadmin/toolkits/model/rapid231/EnUS_Telephony_r2.3.1-8kHz-diarization.pset -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.packageFile=/home/streamsadmin/toolkits/model/rapid231/EnUS_Telephony_r2.3.1.pkg -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.utterances=/home/streamsadmin/data/ -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.callCenter=67 -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.watsonJobId=1 -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t::WatsonSpeech2Text.numWatsonEngines=3 -g etc/watsonJobConfig2.json output/watsonspeech2text/com.ibm.streamsx.speech2text.callcenter.speechprocessing.watsons2t.WatsonSpeech2Text.sab

streamtool submitjob --jobname DataCenterSink  --embeddedzk -P com.ibm.streamsx.speech2text.callcenter.speechprocessing.datacentersink::DataCenterSink.connPort=21436 output/datacentersink/com.ibm.streamsx.speech2text.callcenter.speechprocessing.datacentersink.DataCenterSink.sab -g etc/dataCenterSinkJobConfig.json 

streamtool submitjob --jobname WavGenerator --embeddedzk output/wavgen/com.ibm.streamsx.speech2text.callcenter.speechprocessing.wavgen.WavGenerator.sab -P moveToDirectory=/tmp/Speech2Text/wavGen/moveToDir -P writeBINLocation=/tmp/Speech2Text/wavGen/writeBin -P writeWAVLocation=/tmp/Speech2Text/wavGen/writeWAV -P writeToDirectory=/tmp/Speech2Text/wavGen/writeToDir -P ffmpegLocation=/home/streamsadmin/ffmpeg/ffmpeg-3.2-64bit-static/ -g etc/wavGeneratorJobConfig.json
