	mkdir -p $STREAMS_CALLCENTER_DATA/packethandler
	mkdir -p $STREAMS_CALLCENTER_DATA/watson
	mkdir -p $STREAMS_CALLCENTER_DATA/datacentersink
	mkdir -p $STREAMS_CALLCENTER_DATA/wavgen/moveToDir
	mkdir -p $STREAMS_CALLCENTER_DATA/wavgen/writeBin
	mkdir -p $STREAMS_CALLCENTER_DATA/wavgen/writeWAV
	mkdir -p $STREAMS_CALLCENTER_DATA/wavgen/writeToDir
	mkdir -p $STREAMS_CALLCENTER_DATA/transcripts
	mkdir -p $STREAMS_CALLCENTER_DATA/test/speechprocessing/pcaps/
	mkdir -p $STREAMS_CALLCENTER_DATA/callstate/